[GLOBAL]
pants_version = "2.3.0"
backend_packages = [
  "pants.backend.python",
#  "pants.backend.python.mixed_interpreter_constraints",
#  "pants.backend.python.lint.bandit",
  "pants.backend.python.lint.black",
#  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.flake8",
#  "pants.backend.python.lint.isort",
#  "pants.backend.python.lint.pylint",
#  "pants.backend.python.typecheck.mypy",
]

[source]
root_patterns = [
  # core libs
  "/st2*/st2*",
  "/st2*/tests",
  # runners
  "/contrib/runners/*_runner/*_runner",
  "/contrib/runners/*_runner/tests",
  # packs
  "/contrib/*/actions",
  "/contrib/*/sensors",
  "/contrib/*/lib",
  "/contrib/*/tests",
]

[python-infer]
inits = true

[black]
version = "black==20.8b1"
# black looks in pyproject.toml by default
#config = pyproject.toml

[flake8]
version = "flake8>=3.7.9,<3.9"
extra_requirements = [
  # license check plugin
  "st2flake8==0.1.0",
]
config = "lint-configs/python/.flake8"
args = [
  "--exclude",
  "contrib/examples,contrib/hello_st2,contrib/packs/tests",
]
