[GLOBAL]
pants_version = "2.3.0"
backend_packages = [
  "pants.backend.python",
#  "pants.backend.python.mixed_interpreter_constraints",
#  "pants.backend.python.lint.bandit",
  "pants.backend.python.lint.black",
#  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.flake8",
#  "pants.backend.python.lint.isort",
  "pants.backend.python.lint.pylint",
#  "pants.backend.python.typecheck.mypy",
]
pants_ignore = [
  ".*/",  # . directories
  "/dist/",
  # TODO: remove these, replace with pyproject.toml
  "dist_utils.py",
  "setup.py",
]

[source]
root_patterns = [
  # core libs
  "/st2*/bin",
  "/st2*/st2*",
  "/st2common/benchmarks/micro",
  "/st2*/tests",
  "/st2tests/integration",  # is this installed as a module?
  # runners
  "/contrib/runners/*_runner/*_runner",
  "/contrib/runners/orquesta_runner/orquesta_functions",
  "/contrib/runners/*_runner/tests",
  # packs
  "/contrib/*/actions",
  "/contrib/*/sensors",
  "/contrib/*/lib",
  "/contrib/*/tests",
  "/st2tests/testpacks/*/actions",
  # lint plugins
  "/pylint_plugins",
  # misc
  "/scripts",
  "/tools",
]

[python-infer]
inits = true

[black]
version = "black==20.8b1"
# black looks in pyproject.toml by default
#config = pyproject.toml

[flake8]
version = "flake8>=3.7.9,<3.9"
extra_requirements = [
  # license check plugin
  "st2flake8==0.1.0",
]
config = "lint-configs/python/.flake8"

[pylint]
version = "pylint==2.6.0"
extra_requirements = [
  # dep used by /pylint_plugins/{api_models,db_models}
  "astroid==2.4.2",
  # not sure where this is used
  #"pylint-plugin-utils>=0.4",
]
config = "lint-configs/python/.pylintrc"
source_plugins = [
  # the /pylint_plugins directory
  "pylint_plugins",
]
args = [
  # needed in st2* components, runners, packs
  "--load-plugins=pylint_plugins.api_models",
  # needed in st2* components, runners
  "--load-plugins=pylint_plugins.db_models",
]
