name: Mongodb Service Example

on:
  push:
    branches:
    - gha-service

jobs:
# Runs all steps on the VM
# The service containers will use host port binding instead of container networking so you access them via localhost rather than the service name
  vm-job:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
        # will assign a random free host port
        - 27017/tcp
        options: --name mongodb

    steps:
    - run: docker ps
      env:
        # use localhost for the host here because we are running the job on the VM.
        # If we were running the job on in a container this would be mongodb
        MONGODB_HOST: localhost
        MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }} # get randomly assigned published port
        MONGODB_ID: ${{ job.services.mongodb.id }}
        MONGODB_NETWORK: ${{ job.services.mongodb.network }}
    - run: docker exec mongodb env
    - run: docker exec mongodb ps -ef
    - run: docker exec mongodb cat /proc/*/environ
    - run: docker exec mongodb which mongod
    # pwd is /
    - run: docker exec mongodb ls /etc
